porting to Python 3.8 but not yet working well
  File "C:/Users/nina/Desktop/FIN4Simulations/Fin4_ABM.py", line 412, in <module>
    config = Configuration(initial_state=initial_conditions, #dict containing variable names and initial values
TypeError: __init__() missing 1 required positional argument: 'user_id'